name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node_version: [12, 14, 15]
                include:
                    - os: macos-latest
                      node_version: 14
                    - os: windows-latest
                      node_version: 14
            fail-fast: false

        name: 'Build&Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
        steps:
            - name: Set git to use LF on Windows
              if: matrix.os == 'windows-latest'
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v2

            - name: Set node version to ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}

            - name: Versions
              run: yarn versions

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn build

            - name: Test
              run: yarn jest --ci --silent --reporters=default --reporters=jest-junit

            - name: Upload test artifact
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: JUnit_${{ matrix.os }}_${{ matrix.node }}_${{ github.sha }}
                  path: junit.xml

    lint:
        runs-on: ubuntu-latest
        name: 'Lint: node-14, ubuntu-latest'
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set node version to 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Prepare
              run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn lint

    audit:
        runs-on: ubuntu-latest
        name: 'Audit: node-14, ubuntu-latest'
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set node version to 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Prepare
              run: yarn install --frozen-lockfile

            - name: Audit dependencies
              run: yarn audit --groups dependencies

            - name: Audit peerDependencies
              run: yarn audit --groups peerDependencies

            - name: Check outdated dependencies
              if: github.ref == 'refs/heads/main'
              run: yarn outdated
